---
title: "Lactate Correlation Paper: Figure 2"
author: "John Santiago"
date: "2022-10-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# [Return to Home Page](https://johncsantiago.github.io/Lactate-Correlation-Project.html)

```{r include = FALSE, message = FALSE}

##Liver Trait Data 
LTD= read.csv("https://raw.githubusercontent.com/johncsantiago/Lactate-Correlation-Manuscript/master/Data/LiverTraitData.csv")

##FunctionalGroups
FG=c(rep("High.Performance",5),rep("Intermediate.Performance",2),rep("Low.Performance",3))
names(FG)=c("FV12","LV12","LV13","FV13","LV11","FN11","FN12","LN11","FN13","LN13")
colors=FG
names(colors)=(FG)
colors[colors=="High.Performance"]="royalblue3"
colors[colors=="Intermediate.Performance"]="gold"
colors[colors=="Low.Performance"]="firebrick"


```


```{r echo=F}

x=LTD$time[LTD$libraryID==paste0(substring(names(FG)[1],1,2),substring(names(FG)[1],4,4))&LTD$time!=0&LTD$time<=6]
y=LTD$alactate[LTD$libraryID==paste0(substring(names(FG)[1],1,2),substring(names(FG)[1],4,4))&LTD$time!=0&LTD$time<=6]
plot(x,y, pch=22, bg=colors[1],col="black",ylim=c(min(na.omit(LTD$alactate)),max(na.omit(LTD$alactate))), ylab= "Lactate (mmol/L)", xlab = "Time (Hours)")
lines(spline(x,y, n = 201,ties = "mean",method="natural"), col = colors[1])
i=2
while(i<=length(FG)){
  x=LTD$time[LTD$libraryID==paste0(substring(names(FG)[i],1,2),substring(names(FG)[i],4,4))&LTD$time!=0&LTD$time<=6]
  y=LTD$alactate[LTD$libraryID==paste0(substring(names(FG)[i],1,2),substring(names(FG)[i],4,4))&LTD$time!=0&LTD$time<=6]
  points(x,y, pch=22, bg=colors[i],col="black")
  lines(spline(x,y, n = 201,ties = "mean",method="natural"), col = colors[i])
  i=i+1
}
legend("topright",unique(names(colors)),fill=unique(colors),bty="n",cex=.75)



```
